### ISSUE TITLE
Dedicated server crashes (Related to Titans)

### ISSUE THREAD

**Issue by Legonzaur** [R2Northstar/NorthstarMods#104]
**Northstar version** : 1.4.0

**Nature of the problem** : Frequent servers crashes caused by script error

**Additional mods installed** : Aldin's Kick List

**Custom Settings/Riffs** : Epilogue disabled

**Gamemode** : Skirmish

Server is running using Wine on Linux

Here are 7 log files that all show the same error : 

```
[info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] Entity is null
[info] [SERVER SCRIPT]  -> soul.soul.lastOwner = player
[info] [SERVER SCRIPT] 
CALLSTACK
*FUNCTION [PilotBecomesTitan()] mp/_titan_transfer.nut line [515]
*FUNCTION [RespawnAsTitan()] mp/_base_gametype_mp.gnut line [462]
```

[nslog2022-01-11 12-22-15.txt](https://github.com/R2Northstar/NorthstarMods/files/7848548/nslog2022-01-11.12-22-15.txt)
[nslog2022-01-10 03-22-40.txt](https://github.com/R2Northstar/NorthstarMods/files/7848547/nslog2022-01-10.03-22-40.txt)
[nslog2022-01-09 22-14-26.txt](https://github.com/R2Northstar/NorthstarMods/files/7848546/nslog2022-01-09.22-14-26.txt)
[nslog2022-01-09 17-43-12.txt](https://github.com/R2Northstar/NorthstarMods/files/7848545/nslog2022-01-09.17-43-12.txt)
[nslog2022-01-09 14-53-44.txt](https://github.com/R2Northstar/NorthstarMods/files/7848551/nslog2022-01-09.14-53-44.txt)
[nslog2022-01-09 13-15-15.txt](https://github.com/R2Northstar/NorthstarMods/files/7848550/nslog2022-01-09.13-15-15.txt)
[nslog2022-01-09 00-41-44.txt](https://github.com/R2Northstar/NorthstarMods/files/7848549/nslog2022-01-09.00-41-44.txt)

**Comment by cpdt** [comment]
This might be caused by respawning with your titan after the game has ended, during the "cooloff" period. Haven't tried to replicate this yet but I'm fairly sure I caused my skirmish server to crash by doing that.

**Comment by ASpoonPlaysGames** [comment]
Will try to reproduce, that sounds like something that could be the case

**Comment by ASpoonPlaysGames** [comment]
Yeah found a crash, if you hold your respawn with titan until the fade to black is happening and then use it when players should all be frozen, you get this
![image](https://user-images.githubusercontent.com/66967891/150338966-fa7254b6-20a0-4c97-91f0-cc952c4864d2.png)

**Comment by ASpoonPlaysGames** [comment]
looks like this is a potentially different issue that happened to coincide with what i was doing, this seems to be happening not just in the fade to black, probably something to do with me being the only player in the game?

**Comment by ASpoonPlaysGames** [comment]
![image](https://user-images.githubusercontent.com/66967891/150341459-3ad2128e-afec-44e5-a84f-7dd1dece000a.png)
this is the line that's doing it, looks like a simple fix, it's trying to call an array index that is the array's length, a little -1 should fix
