### ISSUE TITLE
Refuse to let people use the Respawn Dev logo

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [R2Northstar/NorthstarMods#128]
It's confusing so I think we should lock it, both client-side and server-side.

obviously, someone could remove this restriction trivially. but it would cause a bit less confusion.

if any respawn devs get in contact we can whitelist them or something.

**Comment by BobTheBob9** [comment]
i think it'd be better not to restrict this, since it'd basically just make the dev badge exclusive to those that know how to bypass it, making it more exclusive would likely make people assume more easily that those with the dev badge are actually devs, vs if everyone can just get it
