### ISSUE TITLE
Skirmish crash when trying to respawn with no teammates alive (i think)

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarMods#133]
![image](https://user-images.githubusercontent.com/66967891/150064711-5dfd9c6a-4e22-4984-b55e-85a4af0db671.png)
consistently happens when im in a lobby with myself, doesnt happen with a teammate as far as i can tell

**Comment by x3Karma** [comment]
get friends

**Comment by ASpoonPlaysGames** [comment]
thanks ill work on that

**Comment by BobTheBob9** [comment]
should be fixed as of [this commit](https://github.com/R2Northstar/NorthstarMods/commit/c315600b13c92372d0ae0765ce9c1fc5bbd16dc3)
