### ISSUE TITLE
Permadeath modes doesn't show killcam as intended

### ISSUE THREAD

**Issue by x3Karma** [R2Northstar/NorthstarMods#14]
Permadeath modes like Live Fire or Fastball will show your own perspective in the killcam instead of the attacker who killed you.

the value attacker.GetIndexForEntity() is being ignored when running the function PlayerWatchesKillReplay

script is in vscript/mp/_base_gametpe_mp_gnut, around line 361

**Comment by x3Karma** [comment]
Additional info found, this only happens when respawning is not available to the player. Such as Epilogue or Permadeath modes. My guess is that the preparations for respawning a player is not running and therefore a code that shows killcam bugged out

**Comment by x3Karma** [comment]
![image](https://user-images.githubusercontent.com/22678145/147494053-4a7b0d6c-a4d0-4699-bb98-6b37e84e0516.png)
// quick note: in cases where player.Die() is called: e.g. for round ends, player == attacker

**Comment by BobTheBob9** [comment]
is this specifically concerning bugs with normal killcams or exclusively roundwinning killcams?

**Comment by x3Karma** [comment]
Fixed with your patch.
