### ISSUE TITLE
Various Missing Earn Meter Rewards

### ISSUE THREAD

**Issue by connieprice** [R2Northstar/NorthstarMods#148]
- [ ] Inserting Batteries 
- [x] Hardpoint capture events

(I'll add more if more come to my mind.)

Please comment on this issue with any more so we have a somewhat documented list of what's missing.

**Comment by abarichello** [comment]
https://youtu.be/Z4sOU0dCqrg?t=18

**Comment by RoyalBlue1** [comment]
i have all hardpoint values from testing with @pg9812 and am currently working on a branch implementing them
https://gist.github.com/RoyalBlue1/0d101beea7174ae500716b725c3cab92

**Comment by MiloAkerman** [comment]
@RoyalBlue1 is the battery stuff working?

**Comment by RoyalBlue1** [comment]
My pr is only for amped hardpoint
