### ISSUE TITLE
Error processing game logic, appears every time i click on a server

### ISSUE THREAD

**Issue by ToxicMK2** [R2Northstar/NorthstarMods#15]
![Untitled](https://user-images.githubusercontent.com/96743605/147496715-0ae9fff4-3b1d-4282-a761-1035b193e36a.png)

**Comment by MiloAkerman** [comment]
Hello, could you provide some more info on the error? Does it occur all the time or only under specific circumstances? Is your connection good? etc.

**Comment by taskinoz** [comment]
This should no longer be an issue with newer versions of Northstar and the server browser.
Re-open the issue if it comes up on newer versions.
