### ISSUE TITLE
JoinStringArray is called before it is defined

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarMods#150]
![image](https://user-images.githubusercontent.com/66967891/150577518-0a83fd57-fb70-44f3-828b-18b76e1eb947.png)

Might be because JoinStringArray is defined in Northstar.CustomServers whereas it's being called from Northstar.Custom. Is one loaded before the other and therefore causing this?

idk

**Comment by ASpoonPlaysGames** [comment]
this is on current commit on main btw, not current release

**Comment by abarichello** [comment]
Not sure how you got that error, it's working fine for me on master branch

**Comment by ASpoonPlaysGames** [comment]
yeah idk either i just re-downloaded the same commit and its working fine now?

weird
