### ISSUE TITLE
Crash when changing titan mid embark animation

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarMods#153]
https://streamable.com/n8h75u

**Comment by GeckoEidechse** [comment]
Streamable deletes recording after a while if you do not have a premium account so here's a Github mirror. Hope that's ok @ASpoonPlaysGames ?

https://user-images.githubusercontent.com/40122905/151081877-7371eed0-a4b1-4700-9c52-e6676f1302eb.mp4

**Comment by MiloAkerman** [comment]
Succesfully reproduced. Seems to happen when switching from a titan without an arm badge to a titan with an arm badge (might happen viceversa too, not tested). Turns out the code DOESN'T check if your titan actually HAS an arm badge.
