### ISSUE TITLE
Server Crash Report + Client Side Browser List Blank

### ISSUE THREAD

**Issue by Vexbane** [R2Northstar/NorthstarMods#160]
Dedicated Server hard crash without warning, nothing to indicate something is wrong.  When I got kicked, client side (separate pc) I searched on browser for servers + zero showed.  Was interesting that the crashing of the server also affected the client side browser.   I refreshed it a few time still showed zero servers.  Relaunching NorthStar fixed it.

1.  The Crash could have been related with testing Karma.Abuse Mod console commands.  Though it did not crash immediately, it could have been a error in typing with a lag / delay response crash.
2.  The client side issue not showing any servers after the crash / disconnect - is main reason decided to report

https://discord.com/channels/920776187884732556/922663158647255061/935469959818125313 

- **Game Server details:** Time limit and Score Limit set real high so map won't switch or rotate
- **Map:** Glitch
- **Game Mode:** Pilots Vs Pilots
- **Mods installed:**
   - `Barnab.AutoBalance`
   - `HemlockSmartPistolPunishment`
   - `Karma.Abuse`

Physical Server Details:

OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Original Install Date:     3/17/2021, 1:04:40 AM
System Boot Time:          12/15/2021, 7:55:07 PM
System Manufacturer:       Supermicro
System Model:              SYS-5038ML-H8TRF
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3601 Mhz
BIOS Version:              American Megatrends Inc. 2.00, 4/24/2014
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,727 MB
Available Physical Memory: 15,033 MB
Virtual Memory: Max Size:  60,074 MB
Virtual Memory: Available: 20,954 MB
Virtual Memory: In Use:    39,120 MB

[New_Compressed_zipped_Folder.zip](https://github.com/R2Northstar/NorthstarMods/files/7934393/New_Compressed_zipped_Folder.zip)

**Comment by MiloAkerman** [comment]
The text dump you provided does not contain any crashes as far as I can see, and the .dmp gives the following error
![image](https://user-images.githubusercontent.com/40443620/152533842-370dfaad-6d92-432a-8e2d-71479da5e80f.png)

**Comment by ASpoonPlaysGames** [comment]
Closing as stale, and tbh im just confused by this issue?
