### ISSUE TITLE
People get stuck when respawning on panel B on Crash Site in fastball

### ISSUE THREAD

**Issue by laundmo** [R2Northstar/NorthstarMods#170]
like caused by https://github.com/R2Northstar/NorthstarMods/commit/050e707f4762b976791c0934b88779e038f70ade

When people respawn at panel B on Crash Site, they get stuck in place without being able to move. This happened on my Fastball Randomiser server which is using the newest version of [_gamemode_fastball.gnut](https://raw.githubusercontent.com/R2Northstar/NorthstarMods/main/Northstar.Custom/mod/scripts/vscripts/gamemodes/_gamemode_fastball.gnut)

<details>
<summary>Screenshots</summary>

![](https://img.laundmo.com/u/AipGhR.png)

![](https://img.laundmo.com/u/Bmq0J3.png)

</details>

**Comment by GeckoEidechse** [comment]
Should be fixed with #171

**Comment by GeckoEidechse** [comment]
#171 has been merged so this issue should be fixed for now.
