### ISSUE TITLE
Bad spawns on Boomtown and other comp maps (comp ctf, ctf in general )

### ISSUE THREAD

**Issue by KingRacc** [R2Northstar/NorthstarMods#177]
Would be spawned on the wrong side of the map in both halves. 
Spawns in general were in the wrong spots. 

https://www.youtube.com/watch?v=FPdR_1in6LU - just showing how you start on the wrong side of the map tested on all comp legal maps 

https://youtu.be/Isa7ZbQxs_A - An attempted pug. Noticed that some of the spawns weren't right. Only Boomtown. 

We also tested the spawns on normal ctf and it was still messed up

**Comment by GeckoEidechse** [comment]
Completed with #808 :D

Feel free to re-open if there are still issues.
