### ISSUE TITLE
Diceroll Ticks

### ISSUE THREAD

**Issue by IJARika** [R2Northstar/NorthstarMods#188]
-### Bug
When getting ticks with dice roll you only get one, you should receive two like normal ticks.

### Steps to reproduce
1. Get ticks with diceroll.

### Specifications
  - Northstar version: 1.4.0
  - Platform: Steam

**Comment by abarichello** [comment]
This got fixed in https://github.com/R2Northstar/NorthstarMods/pull/71 and is going to be included in the next release

**Comment by ASpoonPlaysGames** [comment]
god damnit i was beaten to it apparently, whoops
