### ISSUE TITLE
Server crash - epilogue - return ( ent.IsNPC() || ent.IsPlayer() ) && IsValid( ent.GetTitanSoul() )

### ISSUE THREAD

**Issue by FrostySn0men** [R2Northstar/NorthstarMods#198]
Server crashes multiple times a day, reportedly usually in epilogue 
[dump_files.zip](https://github.com/R2Northstar/NorthstarMods/files/8052572/dump_files.zip)
[tf2ds_error.txt](https://github.com/R2Northstar/NorthstarMods/files/8052573/tf2ds_error.txt)
[tf2ds_error_b.txt](https://github.com/R2Northstar/NorthstarMods/files/8052574/tf2ds_error_b.txt)

Common error:
[2022-02-11 18:27:32.108] [info] [SERVER SCRIPT]  -> return ( ent.IsNPC() || ent.IsPlayer() ) && IsValid( ent.GetTitanSoul() )
[2022-02-11 18:27:32.108] [info] [SERVER SCRIPT] 
CALLSTACK
*FUNCTION [HasSoul()] titan/sh_titan_soul.gnut line [77]

**Comment by ASpoonPlaysGames** [comment]
Closing as stale
