### ISSUE TITLE
Set mods.json version field via CI on release

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#202]
Currently, `mods.json` has to be manually bumped for releases. Optimally this should be done via CI when creating a release build. Otherwise the field should say `0.0.0-dev` (or `0.0.0` if the former causes an issue with not displaying correctly on clients) when running git revisions directly.

**Comment by abarichello** [comment]
[The CI already does that](https://github.com/R2Northstar/Northstar/blob/31a5919aa4703ef5726b87d6f8f49e8f5c93deb9/.github/workflows/build.yml#L62), i update the fields manually to prevent semver errors when checking out a branch and connecting to a public server.
