### ISSUE TITLE
LTS battery glitch

### ISSUE THREAD

**Issue by knightfire-rdp** [R2Northstar/NorthstarMods#203]
A very annoying LTS battery glitch which ruins the game mode, to clarify, the glitch occurs when the round ends with your pilot holding a battery, after the round ends, throughout the entirety of the match you'll be unable to pick a battery, noticeable by your battery icon appearing on your hud and in your titan.

**Comment by ASpoonPlaysGames** [comment]
Unsure whether it would be best to fix this so that batteries are removed properly from players for all round based modes, or do it on a case-by-case basis for each mode individually

**Comment by Coopyy** [comment]
> Unsure whether it would be best to fix this so that batteries are removed properly from players for all round based modes, or do it on a case-by-case basis for each mode individually

theres no reason not to do for everything cause it breaks batteries. theres no modes that could use that

**Comment by ASpoonPlaysGames** [comment]
Yeah I have done it for everything, if modders want to do weird shit with batteries, they can deal with it

**Comment by Coopyy** [comment]
theyd kinda have to store if a player has battery between rounds themselves cause it breaks otherwise :trollface:

**Comment by Coopyy** [comment]
why the FUCK is that a github emote
