### ISSUE TITLE
Unable to initiate connection to server

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarMods#205]
After cancelling a connection in the server browser, I am then unable to connect to any servers, the spinning wheel doesn't appear or anything (this is in 1.5.0)

**Comment by GeckoEidechse** [comment]
I tried reproducing the bug on `v1.5.0` as you described but was unable to do so:

https://user-images.githubusercontent.com/40122905/153781681-cf1af9ba-6738-4d07-8f91-728417becb91.mp4


Make sure you disabled all mods except the default ones (the `Northstar.XXXXX` ones).

**Comment by ASpoonPlaysGames** [comment]
Ok so I tried to reproduce, and I can't anymore? Might have been due to server version and client version differences or something? Idk

**Comment by GeckoEidechse** [comment]
Aight, closing issue then.
