### ISSUE TITLE
Issues with encoding of Spanish localisation

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#223]
[CI still complains](https://github.com/R2Northstar/Northstar/actions/runs/1855190583) about problems with the encoding of the Spanish localisation file:

![image](https://user-images.githubusercontent.com/40122905/154357481-f81f8820-2251-407c-8ae6-bbc1aabc3719.png)

**Comment by abarichello** [comment]
Not sure what's causing it but at the same time its not really an issue since that file works
