### ISSUE TITLE
Spectator keeps falling out of bounds resulting in massive console dump

### ISSUE THREAD

**Issue by x3Karma** [R2Northstar/NorthstarMods#24]
If you stay dead for a while, this happens
![image](https://user-images.githubusercontent.com/22678145/147653275-fba4bbfb-b855-49af-abcf-78244378c911.png)

**Comment by GeckoEidechse** [comment]
IIRC that should be fixed with `v1.4.0`

**Comment by x3Karma** [comment]
Yup fixed.
