### ISSUE TITLE
Competitive CTF Mode server crash on evac dropship

### ISSUE THREAD

**Issue by L1ghtman2k** [R2Northstar/NorthstarMods#241]
From my understanding, ~~dropship~~ evac ship shouldn't be in competitive CTF in the first place, currently, it is. 

After the animation of the evac ship, the server crashed. Here are the logs:

[mature-oracle.log.zip](https://github.com/R2Northstar/NorthstarMods/files/8104833/mature-oracle.log.zip)

Might not even be the issue with evac ship, might be due to game ending in general

**Comment by GeckoEidechse** [comment]
Drop ship at the start of match or evac ship?

**Comment by L1ghtman2k** [comment]
> Drop ship at the start of match or evac ship?

evac ship, sorry

**Comment by ASpoonPlaysGames** [comment]
Closing as stale
