### ISSUE TITLE
Bug in vanila CTF, during Dropship after halftime

### ISSUE THREAD

**Issue by L1ghtman2k** [R2Northstar/NorthstarMods#242]
Server crashes in vanilla CTF, during halftime, when dropships are dropping players

[mature-oracle.log (1).zip](https://github.com/R2Northstar/NorthstarMods/files/8104859/mature-oracle.log.1.zip)

**Comment by ASpoonPlaysGames** [comment]
Does this still happen? #282 I think should have closed this, but not 100% sure

**Comment by L1ghtman2k** [comment]
Lets close, will reopen if I  run more into this
