### ISSUE TITLE
Respawning with scopeless weapons that crash the game

### ISSUE THREAD

**Issue by patcolyn** [R2Northstar/NorthstarMods#245]
### Bug
Died in a MP game while wielding the Kraber. Respawned with a scopeless Kraber. Firing the weapon without aiming down the sight caused a PlayWeaponParticleEffect error, kicking back to main menu.

I believe the server to be unmodded, have requested details from the server hoster.

### Steps to reproduce
Unknown

### Specifications
  - Northstar version: 1.4
  - Platform: Steam
 
### Video
https://youtu.be/r-lPCHCYu1Y

### Log
[nslog2022-01-16 08-37-31.txt](https://github.com/R2Northstar/Northstar/files/7876625/nslog2022-01-16.08-37-31.txt)

**Comment by BobTheBob9** [comment]
ideally should be fixed as of https://github.com/R2Northstar/NorthstarMods/commit/4582f57a5b82d8c75666010081573df0d86ee03a, but needs testing as i've been unable to verify myself

**Comment by GeckoEidechse** [comment]
Since `v1.6.0` release, to my knowledge we've had no report of spawning with scopeless weapon. So I guess 4582f57a5b82d8c75666010081573df0d86ee03a did fix it.

**Comment by BobTheBob9** [comment]
you love to see it
