### ISSUE TITLE
"Northstar Launcher has crashed!" (LSX)

### ISSUE THREAD

**Issue by WingsOfCoronia** [R2Northstar/NorthstarMods#260]
After playing for 9+ hours, i got this
![Untitled](https://user-images.githubusercontent.com/98377172/156881181-ef701fc3-4f0a-46a2-a472-1a34563b2752.png)

**Comment by RomeoCantCode** [comment]
@WingsOfCoronia after restarting Origin, can you still reproduce this issue? Also you might want to close this and instead do a ticket on Northstar Discord #help so we can do active trouble shooting if you experience this.

If that was a one time issue it probably means your Origin lost connection or similar.

**Comment by WingsOfCoronia** [comment]
> @WingsOfCoronia after restarting Origin, can you still reproduce this issue? Also you might want to close this and instead do a ticket on Northstar Discord #help so we can do active trouble shooting if you experience this.
> 
> If that was a one time issue it probably means your Origin lost connection or similar.

yes i can reproduce the issue, and yes i do re-login Origin but still the same,

**Comment by RomeoCantCode** [comment]
@WingsOfCoronia how can you reproduce it? can you document the steps for us?

**Comment by WingsOfCoronia** [comment]
> @WingsOfCoronia how can you reproduce it? can you document the steps for us?

it's very simple, i just re-launch the Northstar Launcher with or without re-login the Origin, still got the same issue

**Comment by RomeoCantCode** [comment]
https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/troubleshooting#lsx
or restart your PC

**Comment by WingsOfCoronia** [comment]
thanks it's the LSX error one, it's work, thanks for the replies

**Comment by GeckoEidechse** [comment]
Closing as solved then ^^
