### ISSUE TITLE
SCRIPT ERROR: [SERVER] Given ent isn't a player

### ISSUE THREAD

**Issue by sw1p3d** [R2Northstar/NorthstarMods#268]
### Bug
SCRIPT ERROR: [SERVER] Given ent isn't a player

### Steps to reproduce

  1. start up a dedicated server
  2. go out of bounds multiple times, and die to the "tried to flee from battle" timer
  3. repeat until server closes without notice

### Specifications
  - Northstar version: 1.5.0
  - Platform:  Origin

[2022-03-13 14:34:16.102] [info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] Given ent isn't a player.
[2022-03-13 14:34:16.102] [info] [SERVER SCRIPT]  -> Remote_CallFunction_NonReplay( attackerInfo.attacker, "ServerCallback_SetAssistInformation", attackerInfo.damageSourceId, attacker.GetEncodedEHandle(), player.GetEncodedEHandle(), attackerInfo.time ) 
[2022-03-13 14:34:16.102] [info] [SERVER SCRIPT] 
CALLSTACK
*FUNCTION [PostDeathThread_MP()] mp/_base_gametype_mp.gnut line [291]

[2022-03-13 14:34:16.103] [info] [SERVER SCRIPT] LOCALS
[exists] false
[@ITERATOR@] 1
[attackerInfo] unknown struct
[@INDEX@] 0
[alreadyAssisted] TABLE
[methodOfDeath] 211
[attacker] ENTITY (worldspawn [0] at <0 0 0>)
[timeOfDeath] 262.93334960938
[damageInfo] INSTANCE
[player] ENTITY (player sw1p3d [1] (player "sw1p3d" at <-309.268 -8694.45 642.598>))
[this] TABLE

Full Log:
[nslog2022-03-13 13-53-37.txt](https://github.com/R2Northstar/Northstar/files/8240728/nslog2022-03-13.13-53-37.txt)

**Comment by RomeoCantCode** [comment]
Does this also happen if you update to 1.5.1?

**Comment by sw1p3d** [comment]
> Does this also happen if you update to 1.5.1?

testing

**Comment by sw1p3d** [comment]
> Does this also happen if you update to 1.5.1?

I'll have to continually run my server for a while, I'll get back to you tommorow or the day after

**Comment by sw1p3d** [comment]
> Does this also happen if you update to 1.5.1?

Yes, it does still crash

**Comment by Dinorush** [comment]
Can you give an error message of the 1.5.1 version? The crash given in the 1.5.0 log was fixed in 1.5.1 by #215. If the 1.5.1 version gave the same crash error, then you most likely didn't update correctly. If not, then it may truly be an issue in current releases.

**Comment by RomeoCantCode** [comment]
some people had issues with updates recently (seen in ns discord tickets). you might want to delete r2northstar completely, reinstall (fresh) and try again just to make sure. (also cant really tell what the issue was with people needing to delete the folder, maybe the extra files cause some weird behaviour, not sure)

**Comment by sw1p3d** [comment]
[nslog2022-03-16 14-18-23.txt](https://github.com/R2Northstar/NorthstarMods/files/8275924/nslog2022-03-16.14-18-23.txt)


> Can you give a log of the 1.5.1 version crash? The crash given in the 1.5.0 log was fixed in 1.5.1 by #215. If the 1.5.1 version gave the same crash error, then you most likely didn't update correctly. If not, then it may truly be an issue in current releases.

**Comment by Dinorush** [comment]
Yeah. that's a separate error entirely. I'm not sure if it has been fixed or not, though; I suggest asking in the discord or making a separate issue, this one can be closed.

**Comment by GeckoEidechse** [comment]
Closing based on what @Dinorush said.

@sw1p3d if it consistently happens on `v1.5.1`, then please open a new Github issue with updated details and logs.
