### ISSUE TITLE
Separate gamemodes into categories on selection screen

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#270]
The current gamemode selection screen which was taken straight from vanilla is kinda messy. It scatters the available gamemodes over three pages and makes it kinda cumbersome to find the one you're looking for.

![gamemode selection screen](https://user-images.githubusercontent.com/40122905/158479433-804429fb-8c38-4799-8fdd-9cf2b502b554.png)

Instead I'd propose we split up the gamemodes into different categories and then present those categories when selecting _Mode_ in the private match menu screen. Clicking the category in turn reveals the gamemodes of that category. An example setup would be:

```
+---------------------------+
| Vanilla                   |
+---------------------------+
| Northstar Custom          |
+---------------------------+
| Northstar Party           |
+---------------------------+
| Mods                      |
+---------------------------+
```

where:
- **Vanilla:**
  Is the vanilla modes
- **Northstar Custom:**
  Northstar modes like _Fastball_ and _Competitive CTF_
- **Northstar Party:**
  Northstar modes that are more casual, like _Infection_ and _Hide and Seek_
- **Mods:**
   Modes added by 3rd party mods

I think 4-5 categories should be optimal. The above is also only an example, there might be better categories for some of the above. For example vanilla contains a lot of modes and could be split into current Vanilla modes and the ones that were discontinued (like for example _Free For All_).

**Comment by EladNLG** [comment]
this sounds like a thing that I've kiiinda already done? ModSettings basically has all of these features, but is suited for settings instead of gamemodes. I'll gladly look into this after ModSettings gets merged (likely in a long time)

**Comment by uniboi** [comment]
I wanted to abuse this ticket as a test for my scrollable lists ngl

**Comment by RaVenInTheDark** [comment]
> > this sounds like a thing that I've kiiinda already done? ModSettings basically has all of these features, but is suited for settings instead of gamemodes. I'll gladly look into this after ModSettings gets merged (likely in a long time)
> 
> mf be blackmailing me into merging their PR :trollface:

and rightfully so

**Comment by Alystrasz** [comment]
Implemented in https://github.com/R2Northstar/NorthstarMods/pull/624.
