### ISSUE TITLE
Client crashes when respawning in Fastball

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#280]

**Comment by GeckoEidechse** [comment]
Bug was likely introduced in a614d9c52ee1015a340609daa4196613ab37825d as that was the only Fastball related commit since `v1.5.1`.

**Comment by GeckoEidechse** [comment]
Actually as _Infection_ has an issue where players crash out after respawning with the same error message #287 and for both (_Fastball_ and _Infection_) the error happens when calling `StartParticleEffectOnEntity(...)`, the issue is very likely the same.

**Comment by GeckoEidechse** [comment]
https://github.com/R2Northstar/NorthstarMods/blob/main/Northstar.Custom/mod/scripts/vscripts/gamemodes/cl_gamemode_fastball.gnut#L98

**Comment by laundmo** [comment]
looking into this: specifically i think the flaw lies with the change that checks if player is spectator before respawning

ofc everyone respawning in fastball will be a spectator. they still need to respawn for the later logic to work.

**Comment by laundmo** [comment]
> Bug was likely introduced in [a614d9c](https://github.com/R2Northstar/NorthstarMods/commit/a614d9c52ee1015a340609daa4196613ab37825d) as that was the only Fastball related commit since `v1.5.1`.

aight so i figured out that this commit is definitely not at fault, tested reverting it on my server

**Comment by GeckoEidechse** [comment]
Yeah, I'm 99% this and #287 have the same common cause.

**Comment by GeckoEidechse** [comment]
Should be fixed on client with #294
