### ISSUE TITLE
New map selection screen allows selecting maps locked for a certain gamemodes

### ISSUE THREAD

**Issue by Alystrasz** [R2Northstar/NorthstarMods#281]
Previously, some gamemode could lock some maps, for them not to be selectable while playing said gamemode.
With `1.6.0`, this restriction has been removed (why?), letting people play with gamemode/maps associations that weren't planned, and can lead to crashs/strange behaviours (try to play amped hardpoints on coliseum).

The "Hide locked maps" option seems to do nothing (maps list is the same whether option is active or not, see screenshots below).

--- 

![image](https://user-images.githubusercontent.com/11993538/160661380-cb9c29ee-d2e8-4398-9f31-b463c75f86c1.png)

![image](https://user-images.githubusercontent.com/11993538/160661528-eec9f3af-09ec-4fc9-baad-76e7806b3377.png)

**Comment by GeckoEidechse** [comment]
New map selection was added by @F1F7Y

**Comment by F1F7Y** [comment]
hi :)

**Comment by abarichello** [comment]
I forgot to test those combinations when merging :)
Should be easy to fix

**Comment by F1F7Y** [comment]
I only tested the hide locked toggle on coop maps, should be fixed in (#283)[https://github.com/R2Northstar/NorthstarMods/pull/283] :)

**Comment by GeckoEidechse** [comment]
Better to keep the issue open until PR is properly tested and merged ;)
