### ISSUE TITLE
CTF features non-vanilla end-of-round replay for final flag capture in second half

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#286]
The final flag capture in CTF causes a end-of-round replay which is not part of vanilla CTF.
To reproduce, simply capture all flags in CTF.

https://user-images.githubusercontent.com/40122905/161333705-8a6c5f0d-e8df-44e7-b601-a92730d08fad.mp4

**Comment by ASpoonPlaysGames** [comment]
So whilst this is definitely a bug, and needs to be fixed for epilogue reasons, should this be kept for when epilogue is disabled? I think it would be preferred over just a fade to black and the end of the match.

**Comment by BobTheBob9** [comment]
we really just need to disable round winning killreplay for the end of the game if epilogue is on, shouldn't need any ctf-specific logic

**Comment by GeckoEidechse** [comment]
Will be fixed by #296

**Comment by x3Karma** [comment]
@GeckoEidechse i think this should be fine to close now.

**Comment by GeckoEidechse** [comment]
> @GeckoEidechse i think this should be fine to close now.

Yup missed it. Thanks for the heads-up <3
