### ISSUE TITLE
FFA tries to change to 2 team based mode on dedicated server

### ISSUE THREAD

**Issue by F1F7Y** [R2Northstar/NorthstarMods#293]
On a dedicated server FFA tries to change gamemode to a 2 teams based one which causes an error crashing the server
The same issue does not happen on a listen server
![image](https://user-images.githubusercontent.com/64418963/162587819-3ff8fd59-baf6-4a2f-8ec4-6b7fcaa003ba.png)

Check `#ticket-【ＤＥＦＹ】` on discord for more info
I'll try to update this issue if the ticket closes

### Reproducing
1. Fire up a dedicated server running FFA
2. Wait till map change ( or run `GameRules_Endmatch()` to end the match )
3. Crash

**Comment by ASpoonPlaysGames** [comment]
Closing as stale
