### ISSUE TITLE
Dedicated server not displaying in server browser

### ISSUE THREAD

**Issue by Aetrym** [R2Northstar/NorthstarMods#3]
I've opened all necessary ports, set my arguments how I want, but it wont appear.
![Screenshot (57)](https://user-images.githubusercontent.com/96625056/147358741-c12bc2c2-b8fb-4a75-970c-d51b33c29b37.png)
 

Edit: Correction, it does appear but without any of the changes I've made to the dedicated server argument file, and wont allow anyone to connect, myself included.

**Comment by GeckoEidechse** [comment]
As I can see NordVPN open on your task bar, are you by chance running the server over a VPN?

**Comment by GeckoEidechse** [comment]
Closing due to lack of response.

If this is still a problem in particular even when following [the wiki  entry on setting up a server](https://r2northstar.gitbook.io/r2northstar-wiki/hosting-a-server-with-northstar), please reopen this issue <3
