### ISSUE TITLE
Add localisation for version gating

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#304]
With `v1.6.0` we added version gating which causes clients that are considered "out-of-date" by the gate to fail authentication. We do pass this information to the client but on the client it is currently simply shown as "Authentication Failed".

**Comment by emma-miler** [comment]
Ill work on this

**Comment by ASpoonPlaysGames** [comment]
We now show a unique message for different authentication failures, so this can probably be closed

**Comment by GeckoEidechse** [comment]
Ye, that's been completed with #333
