### ISSUE TITLE
Playing Gun Game sets score limit to 28 for all subsequent matches

### ISSUE THREAD

**Issue by xia0** [R2Northstar/NorthstarMods#308]
After a gg match, all subsequent non-round-based matches will have their score limit set to 28.

`GetRoundScoreLimit_FromPlaylist()` and e.g. `GameMode_GetScoreLimit("aitdm")` will return 28.

**Comment by GeckoEidechse** [comment]
Which version of Northstar is that?

**Comment by xia0** [comment]
> Which version of Northstar is that?

1.6.3

The bug can also be replicated when hosting a listen server.
1. start a gg match, end it
2. select any other mode - the score limit will be set to 28
Normally when changing between modes in listen server, the scorelimit is updated appropriately.

**Comment by xia0** [comment]
Likely involving the following lines in _gamemode_gg.nut

	// set scorelimit if it's wrong, sort of a jank way to do it but best i've got rn
	try
	{
		if ( GetCurrentPlaylistVarInt( "scorelimit", GetGunGameWeapons().len() ) != GetGunGameWeapons().len() )
			SetPlaylistVarOverride( "scorelimit", GetGunGameWeapons().len().tostring() )
	}
	catch ( ex ) {}

This may be due to the limitation noted in playlists_v2.txt
`scorelimit 21 // temp until we have a way of dynamically setting non-default scorelimit in code`
