### ISSUE TITLE
UI crash when using console commands in serverbrowser menu

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarMods#314]
![image](https://user-images.githubusercontent.com/66967891/163953291-5068916b-91b8-4368-aabd-9a5bdc8b85cc.png)

unsure if happens with all console commands, but `sv_cheats 1` does it for sure

**Comment by F1F7Y** [comment]
Who broke it
Back when the serverbrowser was still a separate mod I used to have this problem. Fixed it before PR ing it though.

**Comment by GeckoEidechse** [comment]
From testing it still worked just fine in `v1.6.1`. When updating to `v1.6.3` it beaks as mentioned above.

**Comment by GeckoEidechse** [comment]
The only change to serverbrowser code was #295 by @Kaze-Kami, so I guess that's where the bug comes from ^^

**Comment by GeckoEidechse** [comment]
Reverting #295 locally and testing again fixes the bug. So I'm assigning this to @Kaze-Kami <3
Enjoy :P

**Comment by ASpoonPlaysGames** [comment]
Just for some info, the bug seems to come from the button pressed callback for "enter", specifically where GetFocus() doesnt return a hud element due to the console window being opened. I assume it is returning null, shouldn't be too hard to add a check into IsServerButtonFocused

**Comment by GeckoEidechse** [comment]
Seems to be what @F1F7Y did in #315:
https://github.com/R2Northstar/NorthstarMods/pull/315/files#diff-265ac8842998ac03555e80996bdacf126d0717a6570c4b8d9ffb171421c66fa0R567-R568
