### ISSUE TITLE
Incorrect end of game replay perspective in gun game and infection

### ISSUE THREAD

**Issue by Soup-64** [R2Northstar/NorthstarMods#33]
**Description:**
In gun game and infection, the final kill replay uses the wrong kill cam, it should be the camera of the person that got the winning kill.
**Priority:**
Low
**Reasoning:**
The end of game replay showing the perspective of the pilot that got the winning kill is the logical choice and what end users would expect from the behavior.

(edit: wording)

**Comment by ShinaxSISOF** [comment]
I think this meant ppl see the final kill instead of the winning game.
I see that too

**Comment by Soup-64** [comment]
This is ready to merge btw.

**Comment by BobTheBob9** [comment]
fixed as of these commits [here](https://github.com/R2Northstar/NorthstarMods/commit/923ee83f5fa3759f67d331fd693712bd3e91bff7) and [here](https://github.com/R2Northstar/NorthstarMods/commit/8e05a3e8e9967b2ccf2c8e937a946a5b1072217a)
