### ISSUE TITLE
[AITDM] Titan AI behaving weirdly

### ISSUE THREAD

**Issue by xamionex** [R2Northstar/NorthstarMods#334]
I think the video explains it.

https://user-images.githubusercontent.com/57235791/166132649-3e221d3d-0b66-457b-8a68-86183d9a2293.mp4

Not sure why it does this but maybe just some nodes being maybe underground? or too close so the ai doesn't know what to do?

**Comment by F1F7Y** [comment]
@taskinoz

**Comment by ASpoonPlaysGames** [comment]
oh yh I saw that sort of thing in a skirmish game a few days ago, someone managed to also get stuck underneath, seems like there are 2 floors directly on top of each other, and the bottom one needs to be removed from the mesh

**Comment by taskinoz** [comment]
I'll look into it, but was that an autotitan or a piloted one?

**Comment by xamionex** [comment]
> I'll look into it, but was that an autotitan or a piloted one?

In the vid you can notice no-one entered it, so yeah autopilot

**Comment by xamionex** [comment]
BTW, in this part of the map, I saw a titan just phase through a wall and go inside, not sure if it was player-controller though but it seemed like it wasn't.

![image](https://user-images.githubusercontent.com/57235791/166143035-3f1dba28-2957-40d0-b87e-947ba7cf7e51.png)

**Comment by Zanieon** [comment]
Closing this as i can confirm this was a problem with old Navmeshes, new ones don't have the Titans flickering over that specific crate on Drydock anymore.
