### ISSUE TITLE
CTF bugs so far

### ISSUE THREAD

**Issue by L1ghtman2k** [R2Northstar/NorthstarMods#338]
Issues from: https://github.com/R2Northstar/NorthstarMods/blob/c1a3fd2af2fc2bf6e87a92352bf5c9215728cc2f/Northstar.CustomServers/mod/scripts/vscripts/gamemodes/_gamemode_ctf.nut (5/3/2022, reworked spawns branch).

Game Mode: Competitive CTF

1. for some reason the flag is slowly going up every time it is returned/set, which allows repetitive returns: https://streamable.com/909a2t

2. Bad spawns(pretty much exclusively spawning on the enemy flag) https://youtu.be/0gU52QOIzBA

**Comment by L1ghtman2k** [comment]
Spawning titan without full titan meter: https://clips.twitch.tv/TolerantIgnorantBisonRickroll-i-XEjpouG0tBVVX6

**Comment by ASpoonPlaysGames** [comment]
Is this on most recent release or with the stuff that's in testing/incomplete atm?

**Comment by ASpoonPlaysGames** [comment]
Wait nvm you said so at the start i missed that

**Comment by BobTheBob9** [comment]
> Issues from: https://github.com/R2Northstar/NorthstarMods/blob/c1a3fd2af2fc2bf6e87a92352bf5c9215728cc2f/Northstar.CustomServers/mod/scripts/vscripts/gamemodes/_gamemode_ctf.nut (5/3/2022, reworked spawns branch).
> 
> Game Mode: Competitive CTF
> 
>     1. for some reason the flag is slowly going up every time it is returned/set, which allows repetitive returns: https://streamable.com/909a2t
> 
>     2. Bad spawns(pretty much exclusively spawning on the enemy flag) https://youtu.be/0gU52QOIzBA

flag return issues should be fixed now, also pushed some spawn changes so those may be better now

**Comment by GeckoEidechse** [comment]
Between @BobTheBob9 saying flag poll issue has been resolved and #808 fixing spawns, I think it's ok to close this issue as completed. If there are still remaining issues, please re-open or create a new GitHub issue <3
