### ISSUE TITLE
Grappling a player who then phase shifts gets you stuck until you die.

### ISSUE THREAD

**Issue by Erlite** [R2Northstar/NorthstarMods#340]
Reproduction steps:

- Grapple a player
- They phase shift

You'll be stuck, unable to change weapon or stop grappling, forced to look at them until they kill you. Pretty sure I couldn't move or shoot either.

**Comment by x3Karma** [comment]
This should be fixed in https://github.com/R2Northstar/NorthstarLauncher/pull/203.
