### ISSUE TITLE
Server Crash, on round end

### ISSUE THREAD

**Issue by L1ghtman2k** [R2Northstar/NorthstarMods#342]
Seems to occur when one player leaves the lobby before the match ends, while the 2nd player is rewatching the death-cam

[fitting-nighthawk.log.zip](https://github.com/R2Northstar/NorthstarMods/files/8626797/fitting-nighthawk.log.zip)

**Comment by ASpoonPlaysGames** [comment]
closing as stale

**Comment by Dinorush** [comment]
Seems to be fixed as of #516

**Comment by ASpoonPlaysGames** [comment]
closing as completed then, thanks
