### ISSUE TITLE
Client Script Error in ClientCodeCallback_PlayerSpawned() : Cannot set properties on a null

### ISSUE THREAD

**Issue by Legonzaur** [R2Northstar/NorthstarMods#351]
Game Crashed after death 
I don't think I can reproduce this
Gamemode (not sure if relevant): Sticks and Stones
Additional active mods : 
- AWH.InputDisplay
- Ping Leaderboard
- S2.PingDisplay
- S2.SpeedometerV2
```
[2022-05-10 17:27:04.198] [info] [CLIENT SCRIPT] SCRIPT ERROR: [CLIENT] Cannot set properties on a null
[2022-05-10 17:27:04.198] [info] [CLIENT SCRIPT]  -> player.cv.lastSpawnTime = Time()
[2022-05-10 17:27:04.198] [info] [CLIENT SCRIPT] 
CALLSTACK
*FUNCTION [ClientCodeCallback_PlayerSpawned()] client/cl_player.gnut line [185]

[2022-05-10 17:27:04.198] [
info] [CLIENT SCRIPT] LOCALS
[blankDamageHistory] unknown struct
[player] ENTITY (player [3] (player "Legonzaur" at <-527.875 -652.875 20.5>))
[this] TABLE
```

[video](https://cdn.discordapp.com/attachments/934880869393514567/973609923445403688/vlc-record-2022-05-10-17h37m30s-Titanfall_2_2022.05.10_-_16.10.49.01.mp4--49mB-nvenc.mp4)
[nslog2022-05-10 16-07-30.txt](https://github.com/R2Northstar/NorthstarMods/files/8663109/nslog2022-05-10.16-07-30.txt)

**Comment by ASpoonPlaysGames** [comment]
Closing this as stale
