### ISSUE TITLE
Client side crash due to `earn_meter/cl_earn_meter.gnut #338`

### ISSUE THREAD

**Issue by L1ghtman2k** [R2Northstar/NorthstarMods#381]
Happened in an aegis brawl.

Northstar version: 1.7.0

Logs:
[nslog2022-06-01 01-54-22.txt](https://github.com/R2Northstar/NorthstarMods/files/8811733/nslog2022-06-01.01-54-22.txt)

**Comment by JMM889901** [comment]
`[CLIENT] Index "3" is beyond array size of 3`
`entity core = player.GetOffhandWeapons()[3]`
Any specific details about what happened before the crash? did you do something? what titan were you playing?

**Comment by L1ghtman2k** [comment]
No, I don't think I know what have triggerd the issue, nor do I remember preconditions :(

**Comment by Dinorush** [comment]
This should be fixed by #494
