### ISSUE TITLE
Crash when ejecting from a titan in LTS: 

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarMods#394]
![image](https://user-images.githubusercontent.com/66967891/174151076-4ed891b3-96ae-4124-adde-a9d60e8cbe61.png)
[nslog2022-06-16 19-46-54.txt](https://github.com/R2Northstar/NorthstarMods/files/8921948/nslog2022-06-16.19-46-54.txt)

I did also cloak and try and throw a satchel whilst ejecting which may have caused it

**Comment by Dinorush** [comment]
Line 514 has nothing on it in Northstar.Client, so this must be a HUDRevamp crash, not Northstar.

**Comment by ASpoonPlaysGames** [comment]
aight then, @EladNLG hello :)

**Comment by EladNLG** [comment]
@ASpoonPlaysGames send logs

**Comment by ASpoonPlaysGames** [comment]
log is already attached to original comment
