### ISSUE TITLE
Tether traps that are reflected by a vortex shield cannot be destroyed by the team that originally fired them

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarMods#396]
Bug found in LTS, probably exists in all modes though

**Comment by ASpoonPlaysGames** [comment]
closing as stale, and seemingly nobody else has run into this since

**Comment by Dinorush** [comment]
This is an actual issue but not one that is Northstar's responsibility (it is a vanilla bug). Titan Debug has a fix for this for servers that want it.
