### ISSUE TITLE
Error code 4

### ISSUE THREAD

**Issue by TNTBazoom** [R2Northstar/NorthstarMods#4]
I keep getting this error code when trying to start a dedicated server, does anyone know what this means?

**Comment by SIGSTACKFAULT** [comment]
can you show a screenshot of where the error appears?

**Comment by TNTBazoom** [comment]
![pain](https://user-images.githubusercontent.com/96627771/147363274-da8f9d20-14ff-42f1-a87b-02deb67cbb30.PNG)

**Comment by BobTheBob9** [comment]
very late here, but this should be fixed as of newer launcher commits
