### ISSUE TITLE
Missing hardpoint features

### ISSUE THREAD

**Issue by abarichello** [R2Northstar/NorthstarMods#42]
Missing hardpoint features:

- [x] Hardpoint animations when capping
- [ ] HUD popup when inside a cap area (print below)
- [x] Minimap doesnt show icons for the cap areas
- [x] Hardpoint doesn't work on Homestead

![image](https://user-images.githubusercontent.com/16687318/147791582-e0b54498-2423-4ce2-af5f-ab2706a551c1.png)

**Comment by BobTheBob9** [comment]
hardpoint in general honestly needs a rewrite, code is not great

**Comment by x3Karma** [comment]
@GeckoEidechse 
We can close this now I think.

**Comment by RoyalBlue1** [comment]
No the Hud popout is still not there

**Comment by RoyalBlue1** [comment]
Checked wrong version it is there lol
