### ISSUE TITLE
Overflow in `GetOtherTeam()` when switching to FFA map from console

### ISSUE THREAD

**Issue by emma-miler** [R2Northstar/NorthstarMods#420]
## Issue
Switching to a different map from console using the `map` command while the active gamemode is Free For All crashes with the following error.
![](https://cdn.discordapp.com/attachments/368007449095045122/996130794890338484/unknown.png)
This is because the `GetOtherTeam` is being called with an out-of-bounds value, since FFA uses teams to separate players.
Im not entirely sure why or in what context this function is being called, but it should be possible to trace back the crashing call using the built-in stack unwinding functions.

**Comment by ASpoonPlaysGames** [comment]
Cannot reproduce, and a super old issue, so im closing this
