### ISSUE TITLE
Server crashes with Cause: Access Violation

### ISSUE THREAD

**Issue by Vitorvlv** [R2Northstar/NorthstarMods#43]
Log attached
[nslog30-12-2021 18-11-31.txt](https://github.com/R2Northstar/NorthstarMods/files/7794795/nslog30-12-2021.18-11-31.txt)

**Comment by theroylee** [comment]
To echo this, I'm having a similar issue as well where the memory is having access issues in the same location.
[nslog2022-01-06 17-07-29.txt](https://github.com/R2Northstar/NorthstarMods/files/7823787/nslog2022-01-06.17-07-29.txt)

**Comment by RobKBH** [comment]
Yeah I'm also having the same issue.
[nslog2022-01-07 13-31-36.txt](https://github.com/R2Northstar/NorthstarMods/files/7831585/nslog2022-01-07.13-31-36.txt)

**Comment by MrClean6096** [comment]
[nslog2022-01-07 16-57-48.txt](https://github.com/R2Northstar/NorthstarMods/files/7832069/nslog2022-01-07.16-57-48.txt)

**Comment by MiloAkerman** [comment]
You guys have different issues. The real overarching issue here being that Northstar attempts to read memadress 0 when it errors.

@Vitorvlv your crash is likely a duplicate of #64 
@theroylee i have no idea what's up with your crash but looks like the game thinks you have no eyeballs
@RobKBH your crash is pretty straightforward. Game thinks you have no soul.

**Comment by MiloAkerman** [comment]
@RobKBH your bug SHOULD be fixed w #173 
Making a task list for the rest

- [ x ] FP animations have null check instead of IsValid
- [ ]  `rodeo/_rodeo_titan.gnut line 2065: Neither an anim view entity or view offset entity is set.`
- [ ] Player model tries to enter spectator mode while parented to control panel. Dupe of #64?
