### ISSUE TITLE
Serverbrowser gamemodes filter array not localiseable

### ISSUE THREAD

**Issue by F1F7Y** [R2Northstar/NorthstarMods#49]
![image](https://user-images.githubusercontent.com/64418963/147822290-179dcb98-4f82-4770-8464-cf03938fbaa5.png)
`GetPrivateMatchModes()` returns non localisable strings breaking gamemode filter

![image](https://user-images.githubusercontent.com/64418963/147822384-02ec51d5-9373-4b30-991a-a4c53b4e957c.png)
There also seems to be gamemodes missing and at the same time curretly non functional gamemodes like frontier defence are included

Don't have time to fix this so I made this

**Comment by KanjiuAkuma** [comment]
Just had to realize mode is `#PL_private_match` for all servers
So the gamemode filter doesn't work at all actually.

**Comment by KanjiuAkuma** [comment]
Just had to realize this doesn't work at all:
```
void function CheckGamemode( serverStruct t )
{
	if (filterArguments.filterGamemode != "SWITCH_ANY" && filterArguments.filterGamemode == t.serverGamemode)
	{
		file.serversArrayFiltered.append( t )
	}
	else if (filterArguments.filterGamemode == "SWITCH_ANY")
	{
		file.serversArrayFiltered.append( t )
	}
}
```

Because `t.serverGamemode` is always `#PL_private_match`

**Comment by BobTheBob9** [comment]
this should be fixed as of [this commit](https://github.com/R2Northstar/NorthstarMods/commit/b7eae961af2635dfa0411d7271d11f554a31af1b)
