### ISSUE TITLE
Portuguese+German localisations aren't working

### ISSUE THREAD

**Issue by Distion55x** [R2Northstar/NorthstarMods#53]
In release 1.3.0, three new localisation files were added: Russian, portuguese and german. However, out of these 3, only Russian is actually working when you have your game installed in the corresponding language.

**Comment by abarichello** [comment]
I fixed the portuguese translations by moving them from LF to CRLF line endings, I'll add a .gitattribute to fix that for future contributors. Now i'm not sure why the other 2 aren't working

**Comment by abarichello** [comment]
Thanks to https://github.com/R2Northstar/NorthstarMods/pull/26#issuecomment-1003729692
