### ISSUE TITLE
Dying as soon as you complete hacking a terminal on fastball sticks camera in floor

### ISSUE THREAD

**Issue by VITALISED** [R2Northstar/NorthstarMods#55]
If you get killed roughly on the same frame as you finish hacking a terminal, camera will appear in the floor.

**Comment by GeckoEidechse** [comment]
Video of the bug in action:

https://user-images.githubusercontent.com/40122905/148069131-6a29c24e-3f3e-4a47-96ca-8651abda323b.mp4

**Comment by ASpoonPlaysGames** [comment]
I can't reproduce this, so I'm going to close it as stale for now

**Comment by GeckoEidechse** [comment]
Still relevant, see https://github.com/R2Northstar/NorthstarMods/issues/132#issuecomment-1951443648

**Comment by GeckoEidechse** [comment]
cc @Zanieon cause you're an absolute wizard when it comes to this sorta stuff ^^

**Comment by GeckoEidechse** [comment]
Ok nevermind, https://github.com/R2Northstar/NorthstarMods/issues/132#issuecomment-1951443648 is different but feels related
