### ISSUE TITLE
Move `Region` column before server name in server browser

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#552]
Currently `Region` field is the last column in the server browser list

![mp_lobby0017](https://user-images.githubusercontent.com/40122905/204068276-edf190d1-29df-44f2-99b4-ddb2facff923.jpg)

Given that current server names already start with region tag at front, maybe we should mimic that behaviour by just putting region column first.

**Comment by EnderBoy9217** [comment]
Fixed in PR #553

**Comment by F1F7Y** [comment]
Gecko forgor to close issue 💀

**Comment by GeckoEidechse** [comment]
> Gecko forgor to close issue skull

Pro tip, putting `Closes #552` in the PR description instead of a comment auto-closes the corresponding issue on PR merge :P

Anyway, thanks for the reminder, closing as completed ^^
