### ISSUE TITLE
Campaign Freezes

### ISSUE THREAD

**Issue by EnderBoy9217** [R2Northstar/NorthstarMods#563]
Upon launching mission BT-7274 and it completing the loading sequence, the client freezes leading to a blackscreen. No error message occurs during this. This happens both when launching post-tutorial and form main menu,
Further testing needed for other missions.
Tutorial/gauntlet currently works.

Log:
[nslog2023-01-06 20-30-09.txt](https://github.com/R2Northstar/NorthstarMods/files/10365269/nslog2023-01-06.20-30-09.txt)

**Comment by ASpoonPlaysGames** [comment]
Closing as stale
