### ISSUE TITLE
Use standalone Squirrel for CI

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#570]
@RoyalBlue1 wrote some standalone Squirrel stuff that allows running Squirrel files outside of the game. We should really use that to test various Squirrel code in CI.

**Comment by ASpoonPlaysGames** [comment]
Progress is being made on this 
![image](https://user-images.githubusercontent.com/66967891/213021614-e0ac28e5-862d-4ddb-975d-ddb5050cf568.png)
