### ISSUE TITLE
Changing loadouts during dropship intro drops you earlier than expect

### ISSUE THREAD

**Issue by abarichello** [R2Northstar/NorthstarMods#60]
Reproduced this on the current master branch, not sure if its also present on 1.3.0. All you need to do is change loadouts while in the crow dropship and this happens:

https://user-images.githubusercontent.com/16687318/147991336-75e09c38-1521-444a-8616-997946da489b.mp4

**Comment by BobTheBob9** [comment]
respawn actually mentioned this is as a bug in the loadouts code but i assumed it wasn't an issue as of tf2, guess i shouldn't've done that lmao

**Comment by BobTheBob9** [comment]
i can probably just delay loadout changes until intro is over to make this work, i imagine this is what they do ingame

**Comment by hummusbird** [comment]
I looked into this earlier - it's to do with the WaittillAnimEnd function being skipped on loadout change and going straight to the jump anim. Changing loadouts also "resets" a lot of other shit so it's probably worth fixing it at the source.

**Comment by BobTheBob9** [comment]
> I looked into this earlier - it's to do with the WaittillAnimEnd function being skipped on loadout change and going straight to the jump anim. Changing loadouts also "resets" a lot of other shit so it's probably worth fixing it at the source.

i'm relatively certain the animation actually does end because changing loadouts sets your model, so WaittillAnimEnd should actually be skipped

**Comment by hummusbird** [comment]
`SetLoadoutGracePeriodEnabled( false )` - may be the solution here, although not a nice one

**Comment by BobTheBob9** [comment]
the solution i'm going with is delaying loadout changes until after the dropship intro's firstpersonsequence is complete, since this is specifically an issue with anims resetting or something similar on a model change, will see if i can get it working soon

**Comment by hummusbird** [comment]
that's exactly what that function does lol - ill test it now

**Comment by BobTheBob9** [comment]
what i mean specifically is not just disabling loadout grace period entirely, but rather just queue up any requests to set loadouts for grace period, then waiting for intro to finish to set them

**Comment by abarichello** [comment]
Fixed with https://github.com/R2Northstar/NorthstarMods/commit/36c08fa5f800e3fdff4690417ce756c20e6ec8f5
