### ISSUE TITLE
English words in Italian localisation

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#609]
E.g.

- Should be `Giocatori`
  https://github.com/R2Northstar/NorthstarMods/blob/ec992d12ff07db58a6417671a23065ad774c96e1/Northstar.Client/mod/resource/northstar_client_localisation_italian.txt#L275

- Should be `Lista dei Server`
  https://github.com/R2Northstar/NorthstarMods/blob/ec992d12ff07db58a6417671a23065ad774c96e1/Northstar.Client/mod/resource/northstar_client_localisation_italian.txt#L23

**Comment by Alystrasz** [comment]
Both suggestions were submitted through weblate, and we can rely on the community to fix other entries if needed.
