### ISSUE TITLE
spectators in fastball respawn

### ISSUE THREAD

**Issue by L1ghtman2k** [R2Northstar/NorthstarMods#615]
users who spectate game via "Toggle Spectate" respawn.

Also, this same issue happens in Spectator Mod, relevant issue opened there: https://github.com/faky1337/Northstar-Spectator-Mod/issues/4

**Comment by GeckoEidechse** [comment]
Oh snap, given the tourney this is actually quite high severity. Thanks for the heads-up. If you notice more stuff during the tourney please make issues so we can track bugs down and eliminate them <3

**Comment by ASpoonPlaysGames** [comment]
> users who spectate game via "Toggle Spectate" respawn.
Is this respawning on round start, respawn with panels, or both?
