### ISSUE TITLE
Fastball: Getting last kill on player finishing hacking control panel crashes majority of respawning players

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#64]
Getting the kill on the last player in the enemy team just as they finish hacking the control panel crashes the majority of the players respawning from the succesfully hacked control panel.

Video of the bug in action:
(look at the killfeed at the beginning and scoreboard at the end of the clip)

https://user-images.githubusercontent.com/40122905/148071443-7a9c6175-701b-419e-b878-1d7afa1a8e07.mp4

Sadly no logs for the time being, will add them once I have some.

**Comment by F1F7Y** [comment]
Simillar thing happened to me where the player hacking got killed right after respawning his team; round ended even tho my entire team got respawned which could be considered a bug; but mainly noone crashed unlike the linked video

**Comment by GeckoEidechse** [comment]
From personal experience it seems to mainly happen when the killer is using a weapon that has splash damage.

**Comment by GeckoEidechse** [comment]
On that note, I was on the receiving end of the bug recently

**Clip:**

https://user-images.githubusercontent.com/40122905/149836119-fca74066-e72e-4a3d-b3ba-8869db015322.mp4

**Trimmed log:** [(trimmed) nslog2022-01-15 21-50-09.txt](https://github.com/R2Northstar/NorthstarMods/files/7884614/trimmed.nslog2022-01-15.21-50-09.txt)
(`CTRL+F` for `#96` to find the part in the log where the crash happened.)

**Comment by BobTheBob9** [comment]
i think this is caused by the use of GetLocalViewPlayer rather than GetLocalClientPlayer in fastball client scripts, i can try and get a potential fix for this comitted later

**Comment by BobTheBob9** [comment]
should be fixed as of [this commit](https://github.com/R2Northstar/NorthstarMods/commit/917da6226d0aa62717f4ec2abe644589dd8e0e42), leaving the issue open until someone can verify this all works

**Comment by BobTheBob9** [comment]
is this good to close now?

**Comment by GeckoEidechse** [comment]
Haven't experienced the issue again since, so I guess yes ^^
