### ISSUE TITLE
Runtime bug with FD

### ISSUE THREAD

**Issue by t0mn8r** [R2Northstar/NorthstarMods#641]
Hi,
When trying to run a dedicated FD server i get the following runtime error:

```
[20:07:00] [SCRIPT SV] [error] COMPILE ERROR Undefined variable "waveEvents"
[20:07:00] [SCRIPT SV] [error] gamemodes/_gamemode_fd.nut line [518] column [66]
```
from this line in `_gamemode_fd.nut`:
```
	for( int i = GetGlobalNetInt( "FD_currentWave" ); i < waveEvents.len(); i++ )
```
I am hoping someone can fix that above bug which I believe is missing an array definition...

I think that a new fixed version should be created.

I am also looking for a way to do map rotations. I have been looking at these issues for 6 weeks now...

Any assistance is appreciated.

My Discord id is t0mn8r#2095

**Comment by GeckoEidechse** [comment]
What map is this on? Keep in mind that FD is very much in early development and only 3 maps have wave data so far.

**Comment by t0mn8r** [comment]
Hi,

Thanks for the reply.

 

It’s on mp_colony02

**Comment by RoyalBlue1** [comment]
The array should still exist on other maps since it is not defined in map specific files. How did you install the game mode and can you send a log of the crash.

**Comment by t0mn8r** [comment]
Hi Maya,

Thanks for that reply.

 

Installation procedure:

1.	Download TF2 from Steam;
2.	Copy Northstar V1.13.2 to TF2 directory;
3.	Copy NorthstarMods-gamemode_fd to the relevant directories.

 

The log is attached. Modified files are attached.

 

Maybe you could also tell me how to do map rotation…

 

Any assistance is appreciated.

 

Kind regards,

Tom AKA “t0mn8r”

**Comment by t0mn8r** [comment]
When I am able to get into the map the level starts as normal with the intro in the dropship and then comes the drop. It is correctly configured on Wave 1. I am able to walk a few meters and then the game locks up because the server crashed.

HTH

**Comment by t0mn8r** [comment]
OK I am cancelling this bug report because it looks like colony02 doesn't work but homestead and kodai are fine. I will try Rise next.
