### ISSUE TITLE
Why no Titan Turrets in LTS?

### ISSUE THREAD

**Issue by FakahUman** [R2Northstar/NorthstarMods#667]
I asked this a million times when Northstar first came out.  Why can't you use Titan Turrets in LTS?  At first I thought it was due to their AI, like why Attrition took so long.  But then I realized that you can use them in other game modes and they work fine.  So why not LTS?  When you select Titan Turret it defaults to AMPed.  Are you just not aware?  Intentional?

**Comment by ASpoonPlaysGames** [comment]
I intend on looking into this tomorrow (or today technically)
