### ISSUE TITLE
RequiredOnClient warning text is not very clear

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarMods#673]
In the mods menu, there is a warning text that reads "This mod gets (un)loaded automatically"

![image](https://github.com/R2Northstar/NorthstarMods/assets/66967891/fbdc903d-2342-4dbc-81a0-a0c9dbf7b629)

Multiple users have become confused because of this message, thinking that the mod will always get unloaded or something along those lines. 

IMO a better phrasing would read something like: "This mod may get (un)loaded when joining a server"

**Comment by uniboi** [comment]
fair
