### ISSUE TITLE
Killing pilots in attrition is giving 3x times the core charge

### ISSUE THREAD

**Issue by Gityeeter** [R2Northstar/NorthstarMods#682]
There seems to be an issue where killing a pilot in attrition is providing a 15% core charge instead of the expected 5%. This discrepancy impacts balance and provides the team that dropped titan first with significant advantage.

**Comment by EnderBoy9217** [comment]
We need to verify this happens by default and wasn't just a server mod someone had installed.

**Comment by Gityeeter** [comment]
> 

I'm certain this is the behavior in all NS servers. My guess is that killing a pilot gives you 15% titan charge, which seems to carry over and apply for the core charge as well.

**Comment by ASpoonPlaysGames** [comment]
@Gityeeter are there any other discrepancies you can see here? (first value is the overdrive value, second is earn value, third (missing from most) is a core scalar)
