### ISSUE TITLE
Marvins fly when grappled

### ISSUE THREAD

**Issue by abarichello** [R2Northstar/NorthstarMods#69]
When you grapple marvins they forget what gravity is and start floating, they also have text over them that I don't remember existing in the vanilla version

https://user-images.githubusercontent.com/16687318/148127432-da9b701e-cba0-4796-a506-deca4d5d84d9.mp4

**Comment by x3Karma** [comment]
I don't think this is a bug, it's a goddamn feature

**Comment by ASpoonPlaysGames** [comment]
In the vanilla game mrvns just die if you grapple them iirc, shouldn't be hard to implement if we want to

tbh I kinda like it though

**Comment by BobTheBob9** [comment]
while this is great it should probably be fixed, some people in the discord figured out this is likely an issue with ai having their team set to 0, the vanilla game likely uses custom spawning logic to set the teams and stuff up for marvins here so it'd probably be easiest for us to fix this through replicating that

**Comment by BobTheBob9** [comment]
i've tested this, it seems marvins still have this issue regardless of their team

**Comment by H0L0theBard** [comment]
Vanilla Marvins don't get affected by the grapple so it is likely an issue of Marvins being pulled by the grapple when they aren't supposed to. 

https://user-images.githubusercontent.com/97146561/150320861-2d9e62a7-c917-4980-92cb-4639e9f2d40a.mp4

**Comment by x3Karma** [comment]
`entity.kv.contents = (int(entity.kv.contents) | CONTENTS_NOGRAPPLE)`
i wonder if this would fix it

**Comment by x3Karma** [comment]
^ yup that did fixed it will open a pr
