### ISSUE TITLE
cp: Player score for hardpoints

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/NorthstarMods#7]
Amped Hardpoint doesn't have the player scores for hardpoints hooked up.

IIRC, it's something like this (I'm going to verify these soon, but it's been more than a month since I've played a game of AMP; EDIT: unfortunately, I left this too long, and I don't think I'll ever be able to do this now that stryder's borked):

| Event (https://github.com/R2Northstar/NorthstarMods/issues/7#issuecomment-1012448121) | Action | Assault Score | Defense Score |
| --- | --- | --- | --- |
| SCORE_EVENT_HARDPOINT_CAPTURED | Being on the point when captured (if it started from being uncaptured or was captured from the other team) | 250 | 0 |
| SCORE_EVENT_HARDPOINT_CAPTURE_ASSIST | Being on the point when captured (if it started from uncaptured but still biased towards your team) | 100 | 0 |
| TODO: figure out what combination causes this | Amping a point for the first time after capping if it started from being uncaptured or was captured from the other team) (if you have been on the point for at least TODO seconds [or percent?] while amping) | 0 | 250 |
| ^ | Amping a point (for the first time after capping if it started from being uncaptured or was captured from the other team) (if not the above case) | 0 | TODO |
| SCORE_EVENT_HARDPOINT_DEFENSE | Kill opposing team while you and them are on captured point | 0 | 50 |
| SCORE_EVENT_HARDPOINT_PERIMETER_DEFENSE | Kill opposing team while you are on captured point | 0 | 50 |
| SCORE_EVENT_HARDPOINT_HOLD | Amping a captured ally hardpoint (points/second, added to your score every time it hits 10s) | 0 | 2.5 |
| SCORE_EVENT_HARDPOINT_AMPED_HOLD | Holding an amped ally hardpoints (points/second, added to your score every time it hits 10s) | 0 | 5.0 |
| | TODO | |

A few other notes:

- Player list is sorted by combined assault+defense, then by kills, then by whoever reached the score first if it's a tie.

I'll probably try and implement this myself later.

https://github.com/R2Northstar/NorthstarMods/blob/0fa8c57650daa9351f4cc4a153f7642001c7ce05/Northstar.CustomServers/mod/scripts/vscripts/gamemodes/_gamemode_cp.nut
https://github.com/R2Northstar/NorthstarMods/blob/0fa8c57650daa9351f4cc4a153f7642001c7ce05/Northstar.CustomServers/mod/scripts/vscripts/mp/_score.nut

AMP is also missing the point status overlay while sitting on a point (EDIT: #42 was opened for this).

**Comment by abarichello** [comment]
The only sources that I could find online were these:
https://www.reddit.com/r/titanfall/comments/6ewbjz/how_exactly_is_amped_hardpoint_scored/dido3rc/
https://titanfall.fandom.com/wiki/Hardpoint_Domination

The wiki one is from another mode from Titanfall 1 but the points may be similar

**Comment by RoyalBlue1** [comment]
I dumped the score data table and I guess the missing point values are the Assist scores.
but I am not sure when exactly they are awarded.


https://gist.github.com/RoyalBlue1/8aa110131eba1471477d6dd1274dca1f#file-ampedhardpointscoreevents-csv

**Comment by RoyalBlue1** [comment]
There should probable be Titanmeter and Coremeter colums in this table I got these values from the gameplay I found on youtube

https://gist.github.com/RoyalBlue1/0d101beea7174ae500716b725c3cab92

**Comment by pg9182** [comment]
Since stryder's working again, I'd like to test a few things in a public match at some point this week.

**Comment by pg9182** [comment]
https://gist.github.com/RoyalBlue1/0d101beea7174ae500716b725c3cab92
