### ISSUE TITLE
"Toggle Progression" button doesn't appear when using controller

### ISSUE THREAD

**Issue by GoobyMain** [R2Northstar/NorthstarMods#716]
Minor issue lol, here's a link to screenshots: https://imgur.com/a/fWulm1x

It seems like it would be fine to make the toggle progression button triangle/Y or start/options 

Also, while I'm here, I'm pretty sure the pro screen was something you had to unlock for each gun in vanilla? northstar progression doesn't do that

**Comment by ASpoonPlaysGames** [comment]
It looks like the button is there, but just invisible? Very strange.

(Also it should be bound to Y on the controller)

**Comment by ASpoonPlaysGames** [comment]
> Also, while I'm here, I'm pretty sure the pro screen was something you had to unlock for each gun in vanilla? northstar progression doesn't do that

The pro screen is just unlocked based on weapon level? (I believe level 20 or something)

Either way, how things actually get unlocked is not something northstar changes, that stuff exists in vanilla scripts, unless Respawn did a server patch to change it

**Comment by ASpoonPlaysGames** [comment]
> The pro screen is just unlocked based on weapon level? (I believe level 20 or something)

![image](https://github.com/R2Northstar/NorthstarMods/assets/66967891/d5bd49a9-7ee9-4c07-9c4c-04a09ae67242)
Yeah we do unlock pro screens properly
