### ISSUE TITLE
Progression system incorrectly labels items as newly unlocked

### ISSUE THREAD

**Issue by Klemmbaustein** [R2Northstar/NorthstarMods#741]
When playing with progression disabled and when meeting their requirements, some items (banners, weapons skins, etc.) will still be highlighted as if they were just unlocked.

![image](https://github.com/R2Northstar/NorthstarMods/assets/83748124/79a26b03-bac0-42de-a949-1b8740c882a8)

**Comment by Zanieon** [comment]
That happens because DEV_EverythingUnlocked is just a bypass in all lock functions checks, those items are still virtually locked, i'm not sure if anything can be done about it.

**Comment by ASpoonPlaysGames** [comment]
Nah, this should be an easy fix. We can just change the check for newly unlocked items to account for progression preference
