### ISSUE TITLE
Gun game server spams `Invalid enum or item name` in logs

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#749]
![image](https://github.com/R2Northstar/NorthstarMods/assets/40122905/89d6e167-559e-4239-8c38-7c20ef56e8a5)

To reproduce:
1. Start listen server with Gun Game
2. Wait for game to start
3. Check console output

Regression introduced in `v1.19.0`. The previous release (i.e. `v1.18.3`) does not have this. The currently latest release (`v1.19.8`) is still affected by it.

**Comment by ASpoonPlaysGames** [comment]
Not a regression

**Comment by Bobbyperson12** [comment]
This also happens on my infection server. Same reproduction steps.

**Comment by ASpoonPlaysGames** [comment]
Also not a bug
