### ISSUE TITLE
Rework weapon balance and mechanics for competetive CTF

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#818]
## Background

At the moment competitive CTF in Titanfall2 is absolutely dominated by the CAR SMG due to that gun being meta. As such for the Competetive CTF mode that we have in Northstar, it would be nice to work together with the competitive community to rebalance some of the weapons to slightly shift the meta away from the CAR SMG and allow for more varied gun gameplay.

## Some proposals

From DMs between @MrBlaBlak and me:

> 
> My biggest recommendation for CTF is to completely remove aimpunch mechanics from Pilots. Aimpunch is a significant issue for two main reasons:
> 
> 1. ARs become inferior to SMGs: Aimpunch is a much more severe problem when aiming down sights (ADS) with ARs. This disadvantage makes them less competitive compared to SMGs.
>  2. Potential desync due to "aimpunch dust": On top of regular dust effects, "aim punch dust" might be causing desynchronization between the client and server. This can lead to a frustrating feeling of hitting your target on the client-side, while the server-side aimpunch throws your aim off. While the exact reason is unclear, it seems to be connected to aimpunch mechanics.
> 
> &nbsp; 
>
> Regarding the CAR's dominance among SMGs:
> 
> The recent health change to 120 HP has certainly buffed the R-97 (now down to 6 shots to kill) and the Alternator (with 3-shot potential with a headshot). While these are all viable options, the CAR remains the most popular choice. It might be worth investigating balance changes for other SMGs in the future, but first, it would be interesting to see the impact of removing aimpunch entirely.
> 
> Specifically for the Volt:
> 
> One SMG that struggles to compete is the Volt. Here's a suggestion: a slight damage buff at mid and long range. This would better suit its laser-like design, encouraging players to utilize it for long-range fire (e.g., mid-range damage increased from 15 to 17, long-range damage increased from 12 to 14).

## Useful links

Webapp for comparing weapon damage under the current meta: https://ranking-system-fullstack-nextjs.vercel.app/weapons

**Comment by Zanieon** [comment]
Actually i gathered with the Competitive CTF players and they decided that weapon rebalances and mechanics will be better done as mods.
