### ISSUE TITLE
Boosts Bug

### ISSUE THREAD

**Issue by JuniorSmokeBR** [R2Northstar/NorthstarMods#90]
### Bug

- [x] The Amped Weapons Boost does not reload your weapons current ammo count. Normally the boost reloads regardless of being full or not.
- [x] Map Hack Boost has a chance to permanently leave enemies, teammates, and yourself detected throughout the entire game ( if you don't get killed )

**Comment by GeckoEidechse** [comment]
Similarly I've experienced Radar Jammer permanently hiding jamming my minimap.

**Comment by abarichello** [comment]
First point was closed by https://github.com/R2Northstar/NorthstarMods/pull/94
Now I haven't been able to reproduce the infinite Map Hack yet

**Comment by MiloAkerman** [comment]
Is there any logs for when this jammer/maphack bug occurs? Any context for what you might have been doing at the time? It could be that the disabled callback never triggers or that it triggers once but with anomalous values and gets returned early.

**Comment by GeckoEidechse** [comment]
Amped weapons should be fixed by #94 and infinite map hack by #257
