### ISSUE TITLE
Pasting does not work for server passwords

### ISSUE THREAD

**Issue by muckelba** [R2Northstar/NorthstarMods#91]
Nothing happens when i press `ctrl + v` or `rightclick --> paste`. There's no error in the northstar log as well. Would be nice if that gets fixed so people can fill in random/long passwords easier.

**Comment by F1F7Y** [comment]
Tested this, the `textHidden	1` property used to hide the password for some reason disables pasting. Will look into fixing it

**Comment by JJRcop** [comment]
Accordong to tve commit, this issue is fixed
