### ISSUE TITLE
Players can go invisble on Fastball on Wargames

### ISSUE THREAD

**Issue by DerpedCrusader** [R2Northstar/NorthstarMods#92]
This is reproducible, but I don't know the exact steps to make it 100% consistent.

- Start a game of fastball, on wargames
- play until someone is invisible

What i do know, is that it only happens in war games, and no other Maps in fastball (might also be other round based gamemodes)

I assume it has something to do with the death animation, as this map does have a unique one

i do have some mods, but i know that the player is invisible for everyone

you can see it 30 seconds in on this clip

https://www.youtube.com/watch?v=vhdKawb4FGk&t=30s

**Comment by theroylee** [comment]
I just had the glitch happen on eden. It doesn't seem map-dependent.

**Comment by BobTheBob9** [comment]
should be fixed as of [this commit](https://github.com/R2Northstar/NorthstarMods/commit/56f88c797f2c809b7793a7f039b4d44cba49e446), i'd say make another issue if you get a similar bug on non-wargames maps
